name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out el código fuente del repositorio
      - name: Check out code
        uses: actions/checkout@v2

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Iniciar sesión en Docker Hub (opcional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y etiquetar la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t myusername/flask-ci-cd:$GITHUB_SHA .
          docker tag myusername/flask-ci-cd:$GITHUB_SHA myusername/flask-ci-cd:latest

      # Subir la imagen a Docker Hub (opcional)
      - name: Push Docker image
        run: |
          docker push myusername/flask-ci-cd:$GITHUB_SHA
          docker push myusername/flask-ci-cd:latest

      # Desplegar (esto es solo un ejemplo, puedes desplegar en tu servidor o cloud)
      - name: Deploy to Server
        run: |
          echo "Desplegando la aplicación en el servidor"
          # Aquí puedes poner el comando para desplegar tu contenedor
